fedavg_blades:
  run: FEDAVG
  stop:
    training_iteration: 4000
    train_loss: 100000

  config:
    seed:
      grid_search: [111]
    dataset_config:
      type: mnist
      num_clients: 4
      num_classes: 10
      train_batch_size: 64

    evaluation_interval: 50


    num_remote_workers: 2
    num_gpus_per_worker: 0.0
    num_cpus_per_worker: 1
    num_cpus_for_driver: 1
    num_gpus_for_driver: 0.

    global_model: mlp

    server_config:
      aggregator:
        grid_search: [
          type: Mean,
          ]

      optimizer:
        type: SGD
        lr: 0.1
        lr_schedule: [[0, 0.1], [3000, 0.1], [3001, 0.005], [4000, 0.005]]
        momentum:
          grid_search: [0.0]

    num_malicious_clients:
      grid_search: [1]
    adversary_config:
      grid_search:
        - type: blades.adversaries.LabelFlipAdversary
